### ISSUE TITLE
Milner type system

### ISSUE THREAD

**Issue by brucou** [askucher/types#1]
Before reimplementing something that is already done, I wanted to ask you about the expressivity of the types you can validate with your library. I am not so fluent is livescript unfortunately to go look at the source code.

I see examples that seem to build complex types from basic types so I was wondering how far does it go. For instance, can I express : 

- `Stream T` where `Stream` is a type constructor `T -> Stream T`
- I understand you cannot validate function types. Is that correct? You would have to execute the function to check its return type for instance. But can you still validate the params that the function receives against the function signature (from inside the function body of course)?

Or maybe a more complex example will be more clear. I currently have those types (you can replace `Hashmap _ T` by the typical javascript object with values of type `T`, same for `Record`). Can I check the signature of `makeFSM` with your library? That would be so awesome, instead of me writing my own (or worse, using typescript).

## Composed types
- `makeFSM :: Events -> Transitions -> StateEntryComponents -> FSM_Settings -> Component`
- `FSM_Settings :: Record {
     initial_model :: FSM_Model
     init_event_data :: Event_Data 
     sinkNames :: [SinkName]
   }`
- `Sources :: HashMap SourceName (Source *)`
- `Events :: HashMap EventName Event`
- `Event :: Sources -> Source EventData`
- `Transitions :: HashMap TransitionName TransitionOptions`
- `Request : Record {
    command :: Command
    payload :: Payload
  }`
- `ActionRequest : Record {
    driver :: SinkName | ZeroDriver
    request :: (FSM_Model -> EventData) -> Request
  }`
- `UpdateOperation :: JSON_Patch`
- `TransitionOptions :: Record {
    origin_state :: State
    event :: EventName
    target_states :: [Transition]
  }`
- `Transition :: Record {
    event_guard :: EventGuard 
    action_request :: ActionRequest
    transition_evaluation :: [TransEval]
  }`
- `TransEval :: Record {
    action_guard :: ActionGuard
    target_state :: State
    model_update :: FSM_Model -> EventData -> ActionResponse -> [UpdateOperation]     
  }`
- `ActionGuard :: ActionResponse -> Boolean`
- `EventGuard :: Model -> EventData -> Boolean`
- `StateEntryComponents :: HashMap State StateEntryComponent`
- `StateEntryComponent :: FSM_Model -> Component`
- `JSON_Patch :: Op_Add | Op_Remove | Op_Replace | Op_Move | Op_Copy | Op_Test`
- `Op_Add :: Record { op: "add", path: JSON_Pointer, value : *}`
- `Op_Remove :: Record { op: "remove", path: JSON_Pointer}`
- `Op_Replace :: Record { op: "replace", path: JSON_Pointer, value: *}`
- `Op_Move :: Record { op: "move", from: JSON_Pointer, path: JSON_Pointer}`
- `Op_Copy :: Record { op: "move", from: JSON_Pointer, path: JSON_Pointer}`
- `Op_Test :: Record { op: "test", path: JSON_Pointer, value: *}`

## Terminal types
- `FSM_Model :: Object`
- `Payload :: *`
- `EventData :: *`
- `Command :: String`
- `EventName :: String`
- `SinkName :: String`
- `State :: String`
- `ZeroDriver` :: "_"

**Comment by askucher** [comment]
Hey @brucou 



Thank you for your interest. Sorry about late answer

Composed Type in current context is just JSON

There is only one useful use case for this library is to validate incoming JSON (req.body) inside expressJS RESTful method.

Personally I hate JSON schema and combine logic with validation code. And experience says that Types can be reused cross-application. 

So you can create the external file and store types there and use in order to validate all your RESTful services.



This is life example in one of user validation. 


```ocaml

UserProfile
------------
name           : String Range(3,20)
location       : String Range(3,100)
position       : String Range(1,100)
picture        : String Range(3,100)
offer          : Missing | Offer
interests      : [Interest]
email          : String | Missing

RegisterForm
------------
email          : Email
password       : Password
passwordRepeat : Password
profile        : UserProfile

```

I love:
* to define the Type and use it everywhere. 
* to use "OR" for types. 
* to define array like wrapper for type [Interest]

By the way. This is code block for this project http://widebate.com

**Comment by askucher** [comment]
Please close this issue if you found the answer

**Comment by ceremcem** [comment]
@askucher Does widebate.com have an issue page? Is it still being maintained?
